trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

variables:
  # Reference variable group containing secrets and configuration
  - group: 'headless-demo-frontend-fork'

steps:
  - task: Bash@3
    displayName: 'Trigger fork repository synchronization'
    inputs:
      targetType: inline
      script: |
        echo "Triggering fork synchronization for branch: $(Build.SourceBranchName)"

        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $FORK_ACCESS_TOKEN" \
          $FORK_REPOSITORY_URL/dispatches \
          -d "{\"event_type\":\"sync-request\", \"client_payload\": {\"branch\": \"$(Build.SourceBranchName)\"}}"
    env:
      FORK_ACCESS_TOKEN: $(FORK_ACCESS_TOKEN)
      FORK_REPOSITORY_URL: $(FORK_REPOSITORY_URL)
